apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: order-management:latest #Replace with your container image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

--- 
apiVersion: v1
kind: Service
metadata:
  name: order-management-service
spec:
  selector:
    app: order-management
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer