name: CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Docker Build
        run: docker build -t order-management:latest .

      - name: Analyze and Report Tests Results
        uses: dorny/test-reporter@v1
        if: success()
        with:
            name: JUnit Tests
            path: '**/target/surefire-reports/*.xml'
            reporter: java-junit
